# Generated by Django 5.1.15 on 2026-07-16 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_quiz', '0002_aiquestion_correct_indices'),
        ('content', '0007_formation_branch_formation_level_formation_slug_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiqroanswer',
            new_name='ai_qro_answ_verdict_c180fa_idx',
            old_name='ai_qro_ans_verdict_idx',
        ),
        migrations.RenameIndex(
            model_name='aiqroanswer',
            new_name='ai_qro_answ_user_id_306b2c_idx',
            old_name='ai_qro_ans_user_sub_idx',
        ),
        migrations.RenameIndex(
            model_name='aiquestion',
            new_name='ai_quiz_que_job_id_d65c1f_idx',
            old_name='ai_quiz_q_job_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='aiquizjob',
            new_name='ai_quiz_job_status_dfcbb7_idx',
            old_name='ai_quiz_job_status_idx',
        ),
        migrations.RenameIndex(
            model_name='aiquizjob',
            new_name='ai_quiz_job_module__b08048_idx',
            old_name='ai_quiz_job_mod_cre_idx',
        ),
        migrations.AlterField(
            model_name='aiqroanswer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiqroanswer',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Note sur 20 attribuée par Gemini.'),
        ),
        migrations.AlterField(
            model_name='aiquestion',
            name='choices',
            field=models.JSONField(blank=True, default=list, help_text='Pour QCM/QCM_MULTI: liste de 4–5 strings. Vide pour QRO.'),
        ),
        migrations.AlterField(
            model_name='aiquestion',
            name='correct_index',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pour QCM: index de la bonne réponse. Null pour QCM_MULTI et QRO.', null=True),
        ),
        migrations.AlterField(
            model_name='aiquestion',
            name='criteria',
            field=models.JSONField(blank=True, default=list, help_text='Pour QRO: liste de critères ("doit citer X", "doit expliquer Y").'),
        ),
        migrations.AlterField(
            model_name='aiquestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aiquestion',
            name='is_published',
            field=models.BooleanField(default=False, help_text="Passe à True quand l'admin publie ce quiz (recopié dans content.Question)."),
        ),
        migrations.AlterField(
            model_name='aiquestion',
            name='kind',
            field=models.CharField(choices=[('QCM', 'Question à choix multiple (1 bonne réponse)'), ('QCM_MULTI', 'Question à choix multiples (plusieurs bonnes réponses)'), ('QRO', 'Question à réponse ouverte')], max_length=16),
        ),
        migrations.AlterField(
            model_name='aiquizjob',
            name='config',
            field=models.JSONField(default=dict, help_text='Paramètres de génération : nb_questions, ratio_qcm_qro, difficulty.'),
        ),
        migrations.AlterField(
            model_name='aiquizjob',
            name='module',
            field=models.ForeignKey(help_text='Module source du quiz.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_quiz_jobs', to='content.module'),
        ),
        migrations.AlterField(
            model_name='aiquizjob',
            name='raw_ai_output',
            field=models.JSONField(blank=True, default=dict, help_text='Réponse Gemini brute (debug).'),
        ),
        migrations.AlterField(
            model_name='aiquizjob',
            name='resulting_quiz',
            field=models.ForeignKey(blank=True, help_text='Quiz publié à partir de ce job (rempli à la publication).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.quiz'),
        ),
        migrations.AlterField(
            model_name='aiquizjob',
            name='source_ref',
            field=models.CharField(blank=True, help_text='URL YouTube, resource_id PDF, ou vide si texte manuel.', max_length=500),
        ),
        migrations.AlterField(
            model_name='aiquizjob',
            name='source_text',
            field=models.TextField(blank=True, help_text='Texte extrait (transcription YouTube, PDF parsé) ou saisi manuellement.'),
        ),
        migrations.AlterField(
            model_name='aiquizjob',
            name='source_type',
            field=models.CharField(choices=[('VIDEO_YOUTUBE', 'Vidéo YouTube (captions)'), ('PDF', 'Document PDF'), ('MANUAL_TEXT', 'Texte saisi manuellement'), ('MULTI_YOUTUBE', 'Plusieurs vidéos YouTube (examen final)')], max_length=16),
        ),
        migrations.AlterField(
            model_name='aiquizjob',
            name='suggested_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Rang suggéré dans le parcours de la branche (IA-B8).', null=True),
        ),
    ]
