# Generated by Django 5.1.15 on 2026-05-22 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ANNUEL", "Abonnement annuel"),
                            ("BRANCHE_FEMME", "Accès branche Femme"),
                            ("BRANCHE_ENFANT", "Accès branche Enfant"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start", models.DateField()),
                ("end", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("in_tranches", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ADHESION", "Adhésion"),
                            ("COTISATION", "Cotisation"),
                            ("BRANCHE", "Accès branche"),
                            ("TRANCHE", "Tranche d'abonnement"),
                            ("REMBOURSEMENT", "Remboursement"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("VALIDE", "Validé"),
                            ("EN_ATTENTE", "En attente"),
                            ("ECHOUE", "Échoué"),
                        ],
                        max_length=12,
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "swinmo_ref",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.AddIndex(
            model_name="subscription",
            index=models.Index(
                fields=["user", "type", "active"], name="subscriptio_user_id_368c87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "type", "status"], name="payments_user_id_f14f7c_idx"
            ),
        ),
    ]
