# Generated by Django 5.1.15 on 2026-05-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('INSCRIPTION', "Droit d'inscription"), ('COTISATION', 'Cotisation mensuelle'), ('DON', 'Don volontaire'), ('REMBOURSEMENT', 'Remboursement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('MEMBRE', 'Membre')], max_length=20),
        ),
    ]
