# Generated by Django 5.1.3 on 2026-06-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_migrate_to_membership_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('billing', models.CharField(choices=[('ANNUEL', 'Annuel (paiement unique)'), ('TRANCHES', 'En tranches mensuelles'), ('MENSUEL', 'Mensuel (renouvellement automatique)')], max_length=10)),
                ('price_total', models.IntegerField(default=0)),
                ('nb_tranches', models.PositiveIntegerField(default=1)),
                ('tranche_amount', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('access_levels', models.JSONField(default=list)),
                ('formation_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['billing', 'name'],
            },
        ),
    ]
