# Generated by Django 5.1.15 on 2026-06-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscriptionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='kind',
            field=models.CharField(choices=[('INSCRIPTION', 'Accès espace membre (annuel)'), ('COTISATION', 'Accès espace membre (mensuel)'), ('BRANCHE_FEMME', 'Accès espace Femme'), ('BRANCHE_ENFANT', 'Accès espace Enfant'), ('DON', 'Don volontaire')], db_index=True, default='INSCRIPTION', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('INSCRIPTION', "Droit d'inscription"), ('COTISATION', 'Cotisation mensuelle'), ('BRANCHE_FEMME', 'Accès espace Femme'), ('BRANCHE_ENFANT', 'Accès espace Enfant'), ('DON', 'Don volontaire'), ('REMBOURSEMENT', 'Remboursement')], max_length=20),
        ),
    ]
