"""Données statiques des questions Mon Histoire (miroir de lib/mon-histoire-questions.ts)."""

PARTS = [
    {
        "id": 1,
        "title": "Identité",
        "questions": [
            ("1_01", "Quel est votre nom complet ? (nom de naissance, noms d'alliance, surnoms)"),
            ("1_02", "Quelle est votre date et votre lieu de naissance ?"),
            ("1_03", "De quelle ethnie, tribu ou peuple êtes-vous originaire ?"),
            ("1_04", "Quelle est ou quelles sont vos nationalités ?"),
            ("1_05", "Quelles langues parlez-vous ? Laquelle est votre langue maternelle ?"),
            ("1_06", "Y a-t-il une signification particulière à votre prénom ? Qui vous l'a donné et pourquoi ?"),
            ("1_07", "Avez-vous un nom traditionnel ou africain ? Quelle est son histoire ?"),
            ("1_08", "Comment les membres de votre famille vous appellent-ils ?"),
            ("1_09", "Comment vous décririez-vous en quelques mots — physiquement et moralement ?"),
            ("1_10", "Quelle est votre couleur, votre musique, votre saison préférée ? Ce que vous aimez le plus dans la vie ?"),
            ("1_11", "À quel groupe social ou communauté vous sentez-vous appartenir le plus ?"),
            ("1_12", "Avez-vous eu plusieurs « vies » ou identités successives (avant/après migration, avant/après mariage, etc.) ?"),
            ("1_13", "Y a-t-il une photo de vous dont vous êtes particulièrement fier(ère) ? Décrivez-la ou joignez-la."),
            ("1_14", "Quel proverbe ou dicton résume le mieux qui vous êtes ?"),
            ("1_15", "Si vous deviez écrire la première phrase de votre autobiographie, quelle serait-elle ?"),
            ("1_16", "Quel aspect de votre personnalité pensez-vous avoir transmis à vos enfants ou proches ?"),
            ("1_17", "Y a-t-il quelque chose que peu de gens savent sur vous et que vous souhaitez partager ici ?"),
        ],
    },
    {
        "id": 2,
        "title": "Arbre généalogique",
        "questions": [
            ("2_01", "Qui était votre père ? Décrivez-le (nom complet, origine, profession, personnalité, ce que vous retenez de lui)."),
            ("2_02", "Qui était votre mère ? Décrivez-la (nom complet, origine, profession, personnalité, ce que vous retenez d'elle)."),
            ("2_03", "Qui était votre grand-père paternel ? Que savez-vous de sa vie ?"),
            ("2_04", "Qui était votre grand-mère paternelle ? Que savez-vous de sa vie ?"),
            ("2_05", "Qui était votre grand-père maternel ? Que savez-vous de sa vie ?"),
            ("2_06", "Qui était votre grand-mère maternelle ? Que savez-vous de sa vie ?"),
            ("2_07", "Avez-vous connaissance de vos arrière-grands-parents ? Quels sont leurs noms et histoires ?"),
            ("2_08", "Y a-t-il des ancêtres remarquables dans votre famille dont on vous a parlé ? Chefs, guérisseurs, forgerons, griottes…"),
            ("2_09", "D'où venait géographiquement la famille de votre père ?"),
            ("2_10", "D'où venait géographiquement la famille de votre mère ?"),
            ("2_11", "Votre famille a-t-elle un totem, un animal ou un symbole clanique ?"),
            ("2_12", "Y a-t-il une légende, un mythe ou une histoire fondatrice dans votre lignée ?"),
            ("2_13", "Avez-vous eu connaissance de migrations ou déplacements importants dans votre famille (colonisation, guerre, exode rural) ?"),
            ("2_14", "Y a-t-il des liens de parenté remarquables (jumeaux, triplés, enfants d'honneur, enfants adoptés dans la tradition) dans votre famille ?"),
            ("2_15", "Avez-vous des photos ou documents anciens (actes, lettres, photos de vos ancêtres) ? Décrivez-les ou joignez-les."),
            ("2_16", "Que représente pour vous le fait d'appartenir à votre lignée ?"),
            ("2_17", "Quelle valeur ou qualité familiale traverse les générations selon vous ?"),
            ("2_18", "Y a-t-il un ancêtre dont vous vous sentez particulièrement proche, dont vous portez l'héritage ?"),
        ],
    },
    {
        "id": 3,
        "title": "Famille proche",
        "questions": [
            ("3_01", "Combien de frères et sœurs avez-vous (ou avez-vous eus) ? Citez-les par ordre de naissance avec leurs prénoms."),
            ("3_02", "Quelle est votre place dans la fratrie ? Qu'est-ce que cela a signifié pour vous ?"),
            ("3_03", "Quel frère ou quelle sœur vous a le plus marqué(e) et pourquoi ?"),
            ("3_04", "Avez-vous été marié(e) ? Dans quelles circonstances avez-vous rencontré votre conjoint(e) ?"),
            ("3_05", "Comment s'est déroulée votre union (mariage traditionnel, civil, religieux) ? Décrivez cette journée."),
            ("3_06", "Comment décririez-vous votre vie de couple ? Quelles ont été vos forces et vos épreuves ?"),
            ("3_07", "Combien d'enfants avez-vous ? Donnez leurs prénoms, dates et lieux de naissance."),
            ("3_08", "Quel souvenir gardez-vous de la naissance de chacun de vos enfants ?"),
            ("3_09", "Comment avez-vous élevé vos enfants ? Quels principes guidaient votre parentalité ?"),
            ("3_10", "Y a-t-il un moment de votre vie familiale qui vous a particulièrement marqué (joie ou épreuve) ?"),
            ("3_11", "Avez-vous des petits-enfants ? Décrivez votre relation avec eux."),
            ("3_12", "Y a-t-il eu des deuils marquants dans votre famille proche ? Comment les avez-vous vécus ?"),
            ("3_13", "Quelle est la tradition ou le rituel familial que vous chérissez le plus ?"),
            ("3_14", "Y a-t-il des membres de votre famille avec qui vous avez perdu le contact ? Auriez-vous quelque chose à leur dire ?"),
            ("3_15", "Quelle est selon vous la chose la plus importante que vous ayez faite pour votre famille ?"),
            ("3_16", "Si vous deviez décrire votre famille en une image, laquelle serait-ce ?"),
            ("3_17", "Y a-t-il une photo de famille dont vous souhaitez raconter l'histoire ? Joignez-la si possible."),
        ],
    },
    {
        "id": 4,
        "title": "Enfance",
        "questions": [
            ("4_01", "Dans quel endroit avez-vous grandi ? Décrivez le lieu (village, quartier, maison, cour)."),
            ("4_02", "De quoi se souvient-on quand on évoque votre enfance dans votre famille ?"),
            ("4_03", "Quel est votre plus ancien souvenir d'enfance ?"),
            ("4_04", "À quoi ressemblait la maison de votre enfance ? Combien étiez-vous à vivre ensemble ?"),
            ("4_05", "Quels jeux pratiquiez-vous étant enfant ? Avec qui jouiez-vous ?"),
            ("4_06", "Y avait-il un adulte (parent, oncle, tante, voisin, griot) qui vous racontait des histoires ? Lesquelles vous ont marqué ?"),
            ("4_07", "Quel était votre plat préféré quand vous étiez enfant ? Qui le préparait ?"),
            ("4_08", "Quels travaux ou responsabilités aviez-vous enfant dans la famille ?"),
            ("4_09", "Aviez-vous peur de quelque chose ? Comment surmontiez-vous cette peur ?"),
            ("4_10", "Quel événement de votre enfance vous a forgé le plus durablement ?"),
            ("4_11", "Avez-vous vécu des moments de grande pauvreté ou au contraire d'abondance ? Racontez."),
            ("4_12", "Y a-t-il eu un événement traumatisant dans votre enfance dont vous souhaitez parler ?"),
            ("4_13", "Quelle fête ou cérémonie de votre enfance vous a le plus marqué(e) (mariage, funérailles, fête religieuse, initiation) ?"),
            ("4_14", "Qui était votre meilleur(e) ami(e) d'enfance ? Que lui est-il arrivé ?"),
            ("4_15", "Comment votre identité culturelle ou ethnique se manifestait-elle dans votre quotidien d'enfant ?"),
            ("4_16", "Y avait-il des règles ou interdits particuliers dans votre famille pendant l'enfance ?"),
            ("4_17", "Quels rêves aviez-vous pour votre avenir quand vous étiez enfant ?"),
            ("4_18", "Si vous pouviez revivre un moment de votre enfance, lequel choisiriez-vous et pourquoi ?"),
            ("4_19", "Y a-t-il des objets, odeurs ou sons qui vous replongent immédiatement dans votre enfance ?"),
            ("4_20", "Qu'est-ce que votre enfance vous a appris que l'âge adulte n'a pas pu vous donner ?"),
        ],
    },
    {
        "id": 5,
        "title": "Parcours scolaire",
        "questions": [
            ("5_01", "À quel âge avez-vous commencé l'école ? Dans quelle école ? Quel en est votre premier souvenir ?"),
            ("5_02", "Quelles écoles, collèges, lycées ou universités avez-vous fréquentés ?"),
            ("5_03", "Quelles matières aimiez-vous le plus ? Lesquelles vous posaient problème ?"),
            ("5_04", "Qui était votre enseignant(e) préféré(e) et pourquoi ?"),
            ("5_05", "Avez-vous obtenu des diplômes ? Lesquels ? Qu'ont-ils représenté pour vous et votre famille ?"),
            ("5_06", "Avez-vous dû interrompre vos études à un moment ? Pour quelles raisons ?"),
            ("5_07", "Avez-vous eu accès à une formation en dehors de l'école officielle (apprentissage traditionnel, formation professionnelle) ?"),
            ("5_08", "Y avait-il des livres, des bibliothèques ou des ressources culturelles dans votre environnement scolaire ?"),
            ("5_09", "Quelle a été la plus grande difficulté que vous ayez rencontrée dans votre parcours scolaire ?"),
            ("5_10", "L'école vous a-t-elle mis en contact avec des personnes d'autres cultures ou milieux ? Quel impact cela a-t-il eu ?"),
            ("5_11", "Avez-vous eu la chance de faire des études supérieures ? Dans quelle ville ou pays ?"),
            ("5_12", "Comment votre famille a-t-elle soutenu (ou non) votre éducation ?"),
            ("5_13", "Y a-t-il quelque chose que vous n'avez pas pu étudier mais que vous auriez voulu apprendre ?"),
            ("5_14", "Qu'est-ce que l'école vous a donné ? Qu'est-ce qu'elle n'a pas pu vous donner ?"),
            ("5_15", "Quel conseil donneriez-vous aux jeunes de votre famille concernant l'éducation ?"),
            ("5_16", "Si vous étiez à l'école aujourd'hui, qu'étudieriez-vous ?"),
        ],
    },
    {
        "id": 6,
        "title": "Vie professionnelle",
        "questions": [
            ("6_01", "Quel a été votre premier emploi ou votre premier travail rémunéré ?"),
            ("6_02", "Quels métiers, fonctions ou activités avez-vous exercés au cours de votre vie ?"),
            ("6_03", "Quel est le travail dont vous êtes le plus fier(ère) ? Pourquoi ?"),
            ("6_04", "Avez-vous créé quelque chose (une entreprise, une association, un projet) ? Racontez son histoire."),
            ("6_05", "Avez-vous connu le chômage ou des périodes de grande difficulté professionnelle ? Comment les avez-vous traversées ?"),
            ("6_06", "Y a-t-il une rencontre professionnelle qui a changé le cours de votre vie ?"),
            ("6_07", "Avez-vous exercé une activité informelle, artisanale ou agricole qui mérite d'être racontée ?"),
            ("6_08", "Avez-vous migré pour le travail ? Dans quelle(s) ville(s) ou pays avez-vous vécu ?"),
            ("6_09", "Comment conciliiez-vous vie de famille et vie professionnelle ?"),
            ("6_10", "Avez-vous rencontré des discriminations ou injustices dans votre parcours professionnel ?"),
            ("6_11", "Y a-t-il un savoir-faire particulier que vous avez développé et dont vous êtes fier(ère) ?"),
            ("6_12", "Quel a été votre plus grand succès professionnel ?"),
            ("6_13", "Quel a été votre plus grand échec ? Qu'en avez-vous appris ?"),
            ("6_14", "Avez-vous eu des mentors ou des personnes qui vous ont guidé dans votre carrière ?"),
            ("6_15", "À votre retraite ou en fin de carrière, quel bilan faites-vous de votre vie professionnelle ?"),
            ("6_16", "Quels conseils professionnels transmettriez-vous à vos descendants ?"),
            ("6_17", "Y a-t-il une ambition que vous n'avez pas pu réaliser ? Laquelle ?"),
            ("6_18", "Que représente le travail pour vous, au-delà du salaire ?"),
        ],
    },
    {
        "id": 7,
        "title": "Village et culture",
        "questions": [
            ("7_01", "D'où êtes-vous originaire ? Quel est le nom de votre village, de votre quartier ou de votre région d'origine ?"),
            ("7_02", "Décrivez votre village ou lieu d'origine (paysage, climat, végétation, sons, odeurs)."),
            ("7_03", "Quelles sont les traditions ou coutumes importantes de votre peuple ou communauté ?"),
            ("7_04", "Y a-t-il des cérémonies d'initiation ou de passage dans votre culture ? Y avez-vous participé ?"),
            ("7_05", "Quels habits, tenues ou parures traditionnels portez-vous ou avez-vous portés ?"),
            ("7_06", "Quels instruments de musique traditionnels connaissez-vous ? Savez-vous en jouer ?"),
            ("7_07", "Quelles danses ou chants traditionnels font partie de votre héritage culturel ?"),
            ("7_08", "Quels plats ou recettes traditionnels souhaitez-vous transmettre ?"),
            ("7_09", "Quels sont les contes, proverbes ou devinettes que vous avez reçus en héritage ?"),
            ("7_10", "Y a-t-il des lieux sacrés, des arbres, des rivières ou des sites particuliers dans votre culture ?"),
            ("7_11", "Comment les fêtes et cérémonies se déroulaient-elles dans votre village ?"),
            ("7_12", "Comment se transmettait le savoir traditionnel (oral, pratique, initiation) dans votre communauté ?"),
            ("7_13", "Y a-t-il eu des bouleversements dans votre village à cause de la colonisation, de la modernisation ou de l'exode ?"),
            ("7_14", "Que pensez-vous de l'état actuel de votre culture et de vos traditions ?"),
            ("7_15", "Que faites-vous concrètement pour préserver ou transmettre votre culture ?"),
            ("7_16", "Y a-t-il quelque chose dans la culture occidentale que vous avez intégré et quelque chose que vous avez refusé ?"),
            ("7_17", "Quel objet, vêtement ou artisanat représente le mieux votre identité culturelle ?"),
            ("7_18", "Si vous deviez emmener vos descendants dans un seul endroit de votre terre d'origine, ce serait lequel ?"),
        ],
    },
    {
        "id": 8,
        "title": "Vie spirituelle",
        "questions": [
            ("8_01", "Quelle est ou quelles sont vos croyances spirituelles ou religieuses ?"),
            ("8_02", "Dans quelle foi avez-vous été élevé(e) ?"),
            ("8_03", "Y a-t-il eu des moments de doute ou de changement dans votre parcours spirituel ?"),
            ("8_04", "Priez-vous ? Si oui, comment ? À quoi ressemble votre prière ?"),
            ("8_05", "Y a-t-il un ou des guides spirituels (imam, pasteur, prêtre, ancien, féticheur, ancêtre) qui ont marqué votre vie ?"),
            ("8_06", "Croyez-vous aux esprits, aux ancêtres ou à des forces invisibles ? Comment cela se manifeste-t-il dans votre vie ?"),
            ("8_07", "Y a-t-il des pratiques spirituelles ancestrales que vous observez ou avez observées ?"),
            ("8_08", "Avez-vous eu une expérience spirituelle forte — un signe, un rêve, une vision ou un miracle ?"),
            ("8_09", "Comment votre foi vous a-t-elle aidé(e) dans les moments difficiles ?"),
            ("8_10", "Y a-t-il une tension dans votre vie entre la religion et la tradition ? Comment la gérez-vous ?"),
            ("8_11", "Quelles pratiques spirituelles souhaitez-vous transmettre à vos enfants ?"),
            ("8_12", "Quelle est votre vision de la mort, de l'au-delà, du monde des ancêtres ?"),
            ("8_13", "Y a-t-il des interdits, des tabous ou des obligations spirituelles qui structurent votre vie ?"),
            ("8_14", "Que représente la prière ou le recueillement pour vous au quotidien ?"),
            ("8_15", "Si vos descendants ne devaient retenir qu'une chose de votre foi, quelle serait-elle ?"),
            ("8_16", "Y a-t-il quelque chose que vous avez demandé à Dieu ou aux ancêtres et qui s'est réalisé ?"),
        ],
    },
    {
        "id": 9,
        "title": "Le quotidien",
        "questions": [
            ("9_01", "Décrivez une journée type de votre vie actuelle (ou d'une période marquante)."),
            ("9_02", "À quelle heure vous levez-vous habituellement ? Quelles sont vos premières actions de la matinée ?"),
            ("9_03", "Qu'aimez-vous cuisiner ? Avez-vous une recette dont vous êtes particulièrement fier(ère) ?"),
            ("9_04", "Quels sont vos loisirs, passions ou activités de détente préférés ?"),
            ("9_05", "Quel est votre rapport à la musique ? Quels genres ou artistes vous touchent le plus ?"),
            ("9_06", "Lisez-vous ? Quels livres ou auteurs ont compté dans votre vie ?"),
            ("9_07", "Aimez-vous raconter des histoires ou des anecdotes ? Laquelle racontez-vous le plus souvent ?"),
            ("9_08", "Comment vous habillez-vous au quotidien ? Qu'est-ce que cela dit de vous ?"),
            ("9_09", "Avez-vous un jardin, un espace vert ou un rapport particulier à la nature ?"),
            ("9_10", "Comment passez-vous le temps avec vos amis ou voisins ?"),
            ("9_11", "Y a-t-il une habitude ou un rituel quotidien sans lequel vous ne pourriez pas commencer la journée ?"),
            ("9_12", "Avez-vous un animal ou avez-vous eu un animal de compagnie ? Racontez."),
            ("9_13", "Comment vous reposez-vous ? Dormez-vous bien ? Rêvez-vous souvent ?"),
            ("9_14", "Comment gérez-vous votre santé au quotidien (médecine moderne, médecine traditionnelle, deux à la fois) ?"),
            ("9_15", "Y a-t-il un endroit où vous aimez vous retrouver seul(e) pour penser ou vous ressourcer ?"),
            ("9_16", "Qu'est-ce qui vous met vraiment de bonne humeur ?"),
        ],
    },
    {
        "id": 10,
        "title": "Valeurs et sagesse",
        "questions": [
            ("10_01", "Quelles sont les valeurs les plus importantes qui guident votre vie ?"),
            ("10_02", "D'où vous viennent ces valeurs (famille, religion, expérience, rencontre) ?"),
            ("10_03", "Y a-t-il un moment où vous avez dû défendre une valeur au prix d'un grand sacrifice ?"),
            ("10_04", "Comment définissez-vous le respect ? Et l'honneur ?"),
            ("10_05", "Quel est votre rapport à l'argent ? Que vous a-t-on appris sur l'argent ?"),
            ("10_06", "Que pensez-vous du pardon ? Y a-t-il quelqu'un que vous avez pardonné ou à qui vous avez demandé pardon ?"),
            ("10_07", "Quelle leçon de vie avez-vous tirée de votre plus grande épreuve ?"),
            ("10_08", "Y a-t-il quelque chose que vous regrettez et que vous feriez différemment ?"),
            ("10_09", "Comment définissez-vous la réussite ? A-t-elle changé de sens pour vous au fil des années ?"),
            ("10_10", "Que pensez-vous de l'éducation des enfants — trop de liberté, pas assez, juste ce qu'il faut ?"),
            ("10_11", "Quel est selon vous le plus grand danger qui menace notre société ou notre famille ?"),
            ("10_12", "Y a-t-il une injustice que vous avez vécue et qui vous a profondément révolté(e) ?"),
            ("10_13", "Quelle est la chose la plus courageuse que vous ayez faite dans votre vie ?"),
            ("10_14", "Si vous pouviez laisser un seul mot de sagesse à toute l'humanité, lequel serait-ce ?"),
            ("10_15", "Qu'est-ce que vieillir vous a appris ?"),
        ],
    },
    {
        "id": 11,
        "title": "Secrets et savoirs",
        "questions": [
            ("11_01", "Y a-t-il des plantes médicinales, des remèdes ou des recettes de soin que vous connaissez et souhaitez transmettre ?"),
            ("11_02", "Connaissez-vous des pratiques agricoles, artisanales ou techniques ancestrales qui méritent d'être préservées ?"),
            ("11_03", "Y a-t-il un secret de famille que vous avez longtemps gardé et que vous jugez utile de révéler maintenant ?"),
            ("11_04", "Y a-t-il des choses dans votre culture dont on ne parle pas, des sujets tabous que vous souhaitez aborder ici ?"),
            ("11_05", "Connaissez-vous des récits ou histoires que votre communauté a oubliés et que vous souhaitez préserver ?"),
            ("11_06", "Avez-vous reçu un enseignement ésotérique, initiatique ou réservé ? Jusqu'à quel point pouvez-vous le partager ?"),
            ("11_07", "Y a-t-il des noms de lieux (rivières, montagnes, forêts sacrées) et leur signification que vous souhaitez consigner ?"),
            ("11_08", "Connaissez-vous des mots ou expressions dans votre langue qui n'ont pas d'équivalent en français et dont vous voulez expliquer le sens ?"),
            ("11_09", "Y a-t-il des savoir-faire (sculpture, tissage, poterie, forge, pêche, chasse) qui s'éteignent dans votre famille ?"),
            ("11_10", "Avez-vous une recette de longévité ou de bien-vivre que vous attribuez à vos ancêtres ?"),
            ("11_11", "Y a-t-il des histoires de votre enfance concernant des personnes ou des lieux mystérieux que vous voulez raconter ?"),
            ("11_12", "Que savez-vous sur l'histoire de votre peuple avant la colonisation ?"),
            ("11_13", "Y a-t-il des archives, documents ou objets dans votre famille que personne ne sait vraiment lire ou interpréter ?"),
            ("11_14", "Quels savoirs souhaitez-vous absolument que vos descendants ne perdent pas ?"),
            ("11_15", "Y a-t-il un sujet sur lequel vous avez toujours voulu être questionné(e) et que personne ne vous a jamais posé ?"),
        ],
    },
    {
        "id": 12,
        "title": "Les biens",
        "questions": [
            ("12_01", "Avez-vous construit une maison ? Décrivez-la et racontez son histoire."),
            ("12_02", "Y a-t-il des terres, des champs ou des propriétés dans votre famille ? Comment ont-ils été acquis ?"),
            ("12_03", "Quels biens matériels avez-vous accumulés au cours de votre vie dont vous êtes fier(ère) ?"),
            ("12_04", "Y a-t-il des objets de valeur sentimentale dans votre famille (bijoux, habits, ustensiles, instruments) ?"),
            ("12_05", "Comment avez-vous géré votre argent au fil de votre vie ? Y a-t-il des succès ou des échecs financiers importants ?"),
            ("12_06", "Y a-t-il des dettes ou des obligations financières familiales dont vos descendants doivent être informés ?"),
            ("12_07", "Quels biens souhaitez-vous que vos enfants et petits-enfants héritent, et dans quel esprit ?"),
            ("12_08", "Y a-t-il un bien symbolique (une parcelle, une case, un objet) que vous souhaitez voir rester dans la famille ?"),
            ("12_09", "Avez-vous rédigé un testament ou organisé la transmission de vos biens ? Pourquoi ou pourquoi pas ?"),
            ("12_10", "Y a-t-il eu des conflits d'héritage dans votre famille ? Quelles leçons en avez-vous tirées ?"),
            ("12_11", "Quel est, selon vous, le bien le plus précieux qu'on puisse laisser à ses enfants ?"),
            ("12_12", "Y a-t-il des photos, des lettres ou des documents familiaux que vous souhaitez numériser et conserver ?"),
            ("12_13", "Avez-vous contribué à des constructions collectives (école, mosquée, église, forage) dans votre village ?"),
            ("12_14", "Que représente la notion de patrimoine pour vous — matériel et immatériel ?"),
        ],
    },
    {
        "id": 13,
        "title": "Messages aux descendants",
        "questions": [
            ("13_01", "Quel est le message le plus important que vous souhaitez laisser à vos enfants ?"),
            ("13_02", "Y a-t-il quelque chose que vous n'avez jamais pu dire à vos enfants et que vous pouvez dire ici ?"),
            ("13_03", "Que souhaitez-vous pour l'avenir de vos enfants et petits-enfants ?"),
            ("13_04", "Quelles erreurs voudriez-vous leur éviter de commettre ?"),
            ("13_05", "Y a-t-il un conseil que vous avez reçu de vos parents ou grands-parents et que vous voulez à votre tour transmettre ?"),
            ("13_06", "Comment voyez-vous l'identité culturelle de vos descendants dans 50 ans ? Qu'espérez-vous ?"),
            ("13_07", "Qu'est-ce qui, selon vous, unit tous les membres de votre famille malgré les distances et les générations ?"),
            ("13_08", "Y a-t-il une décision dans votre vie que vous avez prise pour vos enfants et qui mérite une explication ?"),
            ("13_09", "Que représente pour vous le fait d'être père, mère, grand-parent ?"),
            ("13_10", "Si vous n'étiez plus là, que voudriez-vous que vos proches fassent chaque année pour se souvenir de vous ?"),
            ("13_11", "Y a-t-il une tradition familiale que vous demandez instamment à vos descendants de perpétuer ?"),
            ("13_12", "Que pensez-vous de la diaspora africaine ? Quel rôle souhaitez-vous que vos descendants y jouent ?"),
            ("13_13", "Y a-t-il un rêve que vous n'avez pas pu réaliser et que vous confiez à vos descendants ?"),
            ("13_14", "Si vous pouviez écrire une lettre à votre arrière-petit-enfant qui naîtra dans 30 ans, que lui diriez-vous ?"),
            ("13_15", "Quelle est la phrase que vous souhaiteriez graver sur votre pierre tombale ou dans les mémoires ?"),
            ("13_16", "Y a-t-il quelqu'un à qui vous souhaitez dédier ce récit ? Pourquoi ?"),
        ],
    },
    {
        "id": 14,
        "title": "Récit libre",
        "questions": [
            ("14_01", "Y a-t-il une partie de votre vie que les questions précédentes n'ont pas abordée et qui vous tient à cœur ?"),
            ("14_02", "Y a-t-il une histoire que vous avez toujours voulu raconter et que personne ne vous a jamais laissé raconter jusqu'au bout ?"),
            ("14_03", "Comment vous sentez-vous après avoir répondu à toutes ces questions ? Qu'est-ce que cet exercice a changé pour vous ?"),
            ("14_04", "Y a-t-il quelqu'un que vous souhaitez remercier dans ce récit ?"),
            ("14_05", "Si vous deviez résumer votre vie en un seul paragraphe, quel serait-il ?"),
            ("14_06", "Avez-vous un document, une photo, un objet particulier à joindre en clôture de ce récit ?"),
            ("14_07", "Souhaitez-vous ajouter quelque chose que vous avez hésité à dire tout au long de ce questionnaire ?"),
        ],
    },
]

# Lookup rapide : question_id -> (part_title, question_text)
QUESTION_INDEX: dict[str, tuple[str, str]] = {}
for _part in PARTS:
    for _qid, _qtext in _part["questions"]:
        QUESTION_INDEX[_qid] = (_part["title"], _qtext)
