# Generated by Django 5.1.15 on 2026-07-15 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoirDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(blank=True, default=dict, help_text='Dictionnaire {question_id: {text, audioTranscript, imageCaptions, structured, notApplicable}}')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis')], default='draft', max_length=20)),
                ('editorial_status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours de rédaction'), ('review', 'En relecture'), ('completed', 'Terminé'), ('archived', 'Archivé')], default='pending', max_length=20)),
                ('editorial_notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memoir_draft', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mémoire — brouillon',
                'verbose_name_plural': 'Mémoires — brouillons',
            },
        ),
    ]
