# Generated by Django 5.1.15 on 2026-05-22 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("BLOCK_USER", "Blocage membre"),
                            ("UNBLOCK_USER", "Déblocage membre"),
                            ("DELETE_POST", "Suppression publication"),
                            ("DELETE_COMMENT", "Suppression commentaire"),
                            ("WARN_USER", "Avertissement membre"),
                            ("MANUAL_PAYMENT", "Validation paiement manuel"),
                            ("GRANT_BRANCH", "Attribution accès branche"),
                            ("REVOKE_BRANCH", "Révocation accès branche"),
                            ("RESET_QUIZ", "Réinitialisation quiz"),
                            ("UPDATE_CONTENT", "Modification contenu"),
                            ("DELETE_CONTENT", "Suppression contenu"),
                            ("EXPORT_DATA", "Export de données"),
                            ("SEND_REMINDER", "Envoi relance"),
                        ],
                        max_length=32,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=50)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
