# Generated by Django 5.1.15 on 2026-05-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('BLOCK_USER', 'Blocage membre'), ('UNBLOCK_USER', 'Déblocage membre'), ('DELETE_POST', 'Suppression publication'), ('DELETE_COMMENT', 'Suppression commentaire'), ('RESOLVE_REPORT', 'Traitement signalement'), ('WARN_USER', 'Avertissement membre'), ('MANUAL_PAYMENT', 'Validation paiement manuel'), ('CLOSE_SUBSCRIPTION', "Clôture d'adhésion (membre)"), ('GRANT_BRANCH', 'Attribution accès branche'), ('REVOKE_BRANCH', 'Révocation accès branche'), ('RESET_QUIZ', 'Réinitialisation quiz'), ('UPDATE_CONTENT', 'Modification contenu'), ('DELETE_CONTENT', 'Suppression contenu'), ('EXPORT_DATA', 'Export de données'), ('SEND_REMINDER', 'Envoi relance')], max_length=32),
        ),
    ]
