# Generated by Django 5.1.15 on 2026-05-24 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("multiple", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "db_table": "quiz_questions",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Formation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("LIVRE", "Livre"),
                            ("FORMATION", "Formation"),
                            ("LIBRE", "Accès libre"),
                        ],
                        default="FORMATION",
                        max_length=10,
                    ),
                ),
                (
                    "access_subscription_types",
                    models.JSONField(blank=True, default=list),
                ),
                ("cover_url", models.URLField(blank=True)),
                ("cover_key", models.CharField(blank=True, max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SCHEDULED", "Programmé"),
                            ("PUBLISHED", "Publié"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "formations",
                "ordering": ["category", "order", "id"],
                "indexes": [
                    models.Index(
                        fields=["category", "status"],
                        name="formations_categor_17220f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "formation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="content.formation",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="content.module",
                    ),
                ),
            ],
            options={
                "db_table": "modules",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="content.module",
                    ),
                ),
            ],
            options={
                "db_table": "courses",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=300)),
                ("is_correct", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="content.question",
                    ),
                ),
            ],
            options={
                "db_table": "quiz_choices",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="QCM", max_length=200)),
                ("pass_threshold", models.PositiveIntegerField(default=15)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz",
                        to="content.course",
                    ),
                ),
                (
                    "formation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_exam",
                        to="content.formation",
                    ),
                ),
            ],
            options={
                "db_table": "quizzes",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="content.quiz",
            ),
        ),
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("validated", models.BooleanField(default=False)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="content.quiz",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quiz_results",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Vidéo"),
                            ("PDF", "PDF"),
                            ("AUDIO", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "video_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("YOUTUBE", "Lien YouTube"),
                            ("UPLOAD", "Fichier hébergé"),
                        ],
                        default="UPLOAD",
                        max_length=10,
                    ),
                ),
                ("youtube_url", models.URLField(blank=True)),
                ("bucket_key", models.CharField(blank=True, max_length=512)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("thumbnail_key", models.CharField(blank=True, max_length=512)),
                ("nb_pages", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_sec", models.PositiveIntegerField(blank=True, null=True)),
                ("size_mo", models.FloatField(blank=True, null=True)),
                ("audio_format", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="content.course",
                    ),
                ),
            ],
            options={
                "db_table": "resources",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="module",
            index=models.Index(
                fields=["formation", "parent", "order"],
                name="modules_formati_1335b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="course",
            index=models.Index(
                fields=["module", "order"], name="courses_module__a6c4d8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="quiz",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("course__isnull", False), ("formation__isnull", True)),
                    models.Q(("course__isnull", True), ("formation__isnull", False)),
                    _connector="OR",
                ),
                name="quiz_course_xor_formation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizresult",
            unique_together={("user", "quiz")},
        ),
    ]
