# Generated by Django 5.1.15 on 2026-05-22 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Vidéo"),
                            ("PDF", "PDF"),
                            ("AUDIO", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("GENERALE", "Générale"),
                            ("FEMME", "Femme"),
                            ("ENFANT", "Enfant"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "collections",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Vidéo"),
                            ("PDF", "PDF"),
                            ("AUDIO", "Audio"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("GENERALE", "Générale"),
                            ("FEMME", "Femme"),
                            ("ENFANT", "Enfant"),
                        ],
                        max_length=10,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("thumbnail_url", models.URLField(blank=True)),
                ("quiz_url", models.URLField(blank=True)),
                ("quiz_threshold", models.PositiveIntegerField(default=15)),
                ("quiz_active", models.BooleanField(default=True)),
                ("bucket_key", models.CharField(blank=True, max_length=512)),
                ("nb_pages", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_sec", models.PositiveIntegerField(blank=True, null=True)),
                ("size_mo", models.FloatField(blank=True, null=True)),
                ("audio_format", models.CharField(blank=True, max_length=10)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contents",
                        to="content.collection",
                    ),
                ),
            ],
            options={
                "db_table": "contents",
                "ordering": ["branch", "order"],
            },
        ),
        migrations.CreateModel(
            name="QuizResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(default=0)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("validated", models.BooleanField(default=False)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_results",
                        to="content.content",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "quiz_results",
            },
        ),
        migrations.AddIndex(
            model_name="content",
            index=models.Index(
                fields=["branch", "content_type", "active"],
                name="contents_branch_32dc95_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="quizresult",
            unique_together={("user", "content")},
        ),
    ]
