# Generated by Django 5.1.15 on 2026-05-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='access_subscription_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
