# Generated by Django 5.1.15 on 2026-06-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('trainer', models.CharField(default='Coach Rodrigue DOUANLA', max_length=150)),
                ('platform', models.CharField(choices=[('YouTube', 'YouTube Live'), ('Zoom', 'Zoom Meeting'), ('Meet', 'Google Meet')], default='YouTube', max_length=10)),
                ('status', models.CharField(choices=[('upcoming', 'À venir'), ('live', 'En cours'), ('replay', 'Replay')], default='upcoming', max_length=10)),
                ('link', models.URLField(blank=True, max_length=512)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'live_sessions',
                'ordering': ['status', '-start_at'],
            },
        ),
    ]
