# Generated by Django 5.1.15 on 2026-05-22 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_backfill_access_subscription_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='thumbnail_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
