# Generated by Django 5.1.3 on 2026-06-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_livesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('branche', models.CharField(choices=[('GENERALE', 'Générale'), ('FEMME', 'Femmes'), ('ENFANT', 'Enfants')], default='GENERALE', max_length=10)),
                ('access_level', models.CharField(choices=[('PUBLIC', 'Public'), ('MEMBRE', 'Membres'), ('FEMME', 'Femmes'), ('ENFANT', 'Enfants')], default='PUBLIC', max_length=10)),
                ('bucket_key', models.CharField(blank=True, max_length=512)),
                ('cover_url', models.URLField(blank=True)),
                ('duration_sec', models.PositiveIntegerField(blank=True, null=True)),
                ('size_mo', models.FloatField(blank=True, null=True)),
                ('audio_format', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_gratuit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'audio_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('branche', models.CharField(choices=[('GENERALE', 'Générale'), ('FEMME', 'Femmes'), ('ENFANT', 'Enfants')], default='GENERALE', max_length=10)),
                ('access_level', models.CharField(choices=[('PUBLIC', 'Public'), ('MEMBRE', 'Membres'), ('FEMME', 'Femmes'), ('ENFANT', 'Enfants')], default='PUBLIC', max_length=10)),
                ('bucket_key', models.CharField(blank=True, max_length=512)),
                ('cover_url', models.URLField(blank=True)),
                ('nb_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('size_mo', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_gratuit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'library_pdfs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='formation',
            name='formations_branch_level_idx',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='level',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='slug',
        ),
        migrations.AddField(
            model_name='livesession',
            name='branche',
            field=models.CharField(choices=[('GENERALE', 'Générale'), ('FEMME', 'Femmes'), ('ENFANT', 'Enfants')], default='GENERALE', max_length=10),
        ),
        migrations.AddField(
            model_name='livesession',
            name='replay_url',
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='platform',
            field=models.CharField(choices=[('YOUTUBE', 'YouTube Live'), ('ZOOM', 'Zoom Meeting'), ('MEET', 'Google Meet'), ('TEAMS', 'Microsoft Teams')], default='ZOOM', max_length=10),
        ),
        migrations.AlterField(
            model_name='livesession',
            name='status',
            field=models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='PLANIFIE', max_length=10),
        ),
    ]
