# Generated by Django 5.1.15 on 2026-05-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_membership_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['category', 'order']},
        ),
        migrations.RemoveIndex(
            model_name='content',
            name='contents_branch_32dc95_idx',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='content',
            name='branch',
        ),
        migrations.AddField(
            model_name='collection',
            name='category',
            field=models.CharField(choices=[('LIVRE', 'Livre'), ('FORMATION', 'Formation'), ('LIBRE', 'Accès libre')], default='FORMATION', max_length=10),
        ),
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(choices=[('LIVRE', 'Livre'), ('FORMATION', 'Formation'), ('LIBRE', 'Accès libre')], default='FORMATION', max_length=10),
        ),
        migrations.AddIndex(
            model_name='content',
            index=models.Index(fields=['category', 'content_type', 'active'], name='contents_categor_1d12d2_idx'),
        ),
    ]
