# Generated by Django 5.1.15 on 2026-07-15 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_formation_repair_slug_branch_level'),
        ('content', '0005_resource_transcript_text'),
    ]

    operations = [
    ]
