# Generated by Django 5.1.15 on 2026-07-16 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_merge_20260715_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='branch',
            field=models.CharField(choices=[('GENERALE', 'Générale'), ('FEMME', 'Femmes'), ('ENFANT', 'Enfants')], default='GENERALE', max_length=10),
        ),
        migrations.AddField(
            model_name='formation',
            name='level',
            field=models.CharField(blank=True, choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('AVANCE', 'Avancé')], max_length=15),
        ),
        migrations.AddField(
            model_name='formation',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddIndex(
            model_name='formation',
            index=models.Index(fields=['branch', 'level'], name='formations_branch_level_idx'),
        ),
    ]
