# Generated by Django 5.1.15 on 2026-07-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_formation_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='criteria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('QCM', 'QCM (une bonne réponse)'), ('QCM_MULTI', 'QCM multi (plusieurs réponses)'), ('QRO', 'Réponse ouverte')], default='QCM', max_length=12),
        ),
    ]
