# Generated by Django 5.1.3 on 2026-06-22 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('branche', models.CharField(choices=[('GENERALE', 'Générale'), ('FEMME', 'Femmes'), ('ENFANT', 'Enfants')], default='GENERALE', max_length=10)),
                ('color', models.CharField(default='#c9a227', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'community_channels',
                'ordering': ['branche', 'name'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='post_status',
            field=models.CharField(choices=[('PUBLIE', 'Publié'), ('MODERE', 'Modéré'), ('ARCHIVE', 'Archivé')], default='PUBLIE', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('ANNONCE', 'Annonce'), ('DISCUSSION', 'Discussion'), ('QUESTION', 'Question')], default='DISCUSSION', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='community.communitychannel'),
        ),
    ]
